# Generated by Django 3.2.1 on 2021-05-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('quote', models.CharField(default=None, max_length=300)),
                ('author', models.CharField(default=None, max_length=100)),
                ('email', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
